### ISSUE TITLE
Ddos telegram bot.

### ISSUE THREAD

**Issue by myideaidea** [Mehliug-git/DDOS_Telegram_BOT#14]
Sir please help me for making Ddos telegram bot.. Please sir.

**Comment by Sahilshaikh1978** [comment]
Ok please contact on telegram  @ll_ALEX_lI

**Comment by soura1sin** [comment]
> Sir please help me for making Ddos telegram bot.. Please sir.

Hello bro, you make ddos telegram bot ?

**Comment by Mehliug-git** [comment]
Only issue here
