### ISSUE TITLE
mhddos_proxy

### ISSUE THREAD

**Issue by AnonAmit** [Mehliug-git/DDOS_Telegram_BOT#15]
It seems there was an issue with cloning the `mhddos_proxy` repository from GitHub. The error message indicates that the repository was not found, possibly due to an incorrect URL, authentication issue, or the repository being private or deleted.

TERMINAL OUTPUT 
```bash
Cloning into 'mhddos_proxy'...                                                                                
Username for 'https://github.com': 
Password for 'https://github.com': 
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/porthole-ascend-cinnamon/mhddos_proxy.git/'
bash: line 30: cd: mhddos_proxy: No such file or directory
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by Mehliug-git** [comment]
WTF, okay I go check this

**Comment by Mehliug-git** [comment]
Okay is just cause the owner of MHDDOS proxy change the name of the repo (+ "_releases" in the name )

I make the changement, can you test it ?

**Comment by Mehliug-git** [comment]
Is not my issue, the error is on python_git_MHDDoS_proxy_install.sh, make the change in this file or open a issue for this file : 


https://raw.githubusercontent.com/SlavaUkraineSince1991/DDoS-for-all/main/scripts/python_git_MHDDoS_proxy_install.sh
