### ISSUE TITLE
Hey I want your help buddy...

### ISSUE THREAD

**Issue by Aarushhe** [Mehliug-git/DDOS_Telegram_BOT#16]

**Comment by Mehliug-git** [comment]
Yeah tell me

**Comment by Bhavin11379** [comment]
Hi Bro, Writing For Ddos Telegram Bot 

So , after copying repo on glitch what next should I do . .env file and numpy variable can you explain in detail please .
Also , it says sudo command not found

**Comment by Mehliug-git** [comment]
please give me your installation steps with command (if possible)

**Comment by Shivam2788** [comment]
Hello bro I'm new at this please give a tutorial for installation process 
Regards
