### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Moi792** [Mehliug-git/DDOS_Telegram_BOT#2]
![image](https://github.com/Mehliug-git/DDOS_Telegram_BOT/assets/80194971/60071214-d5e5-4e67-9475-caf41e3b19bd)

**Comment by Mehliug-git** [comment]
Hi !

Try this : pip3 install subprocess
and send me the output if you have still this error

**Comment by Moi792** [comment]
![image](https://github.com/Mehliug-git/DDOS_Telegram_BOT/assets/80194971/1445afa6-ce57-45de-9107-06653db31ab4)

**Comment by Mehliug-git** [comment]
And Google check the error

**Comment by Moi792** [comment]
it in glitch and i can't sudo apt upgrade ...

**Comment by Mehliug-git** [comment]
Google check the error...

But try something like : 
pip3 install subprocess==3.11.4

Juste find a version number and install it.

**Comment by Mehliug-git** [comment]
Ok I have test with the same problem, I will delete subprocess and re from the requirements.txt file, its useless.
