### ISSUE TITLE
How to run ddos on the telegram bot?

### ISSUE THREAD

**Issue by Bmgpt** [Mehliug-git/DDOS_Telegram_BOT#7]
HI,

I have built the bot net using your source code on Glitch as per what you have documented on Readme.md.

But once I /start on the telegram bot, whats next? Please guide me.

<img width="509" alt="image" src="https://github.com/Mehliug-git/DDOS_Telegram_BOT/assets/137195478/f95ceab6-339a-4e69-9efb-3cdf02cc270e">

**Comment by Mehliug-git** [comment]
Hi ! 

I’m sorry I didn’t put it in the doc lol, I’ll do it.

Make a /help for the internal doc ;) 

Or juste make this : 

`/ddos http://url_of_your_website.com`


You can adjust the timout of the attack with :

`/t NEW_TIMEOUT_IN_SECONDS`

**Comment by Mehliug-git** [comment]
Is OK ?
