### ISSUE TITLE
How can I make the bot start all the others?

### ISSUE THREAD

**Issue by D3xExtaz** [Mehliug-git/DDOS_Telegram_BOT#9]
(je suis fr) Soi just wanted to know how can i have 70 telegram bots and more in the server

**Comment by Mehliug-git** [comment]
(moi aussi haha)

Tout simplement tu fait les max de bots que te propose Telegram (20) et ensuite le reste tu prend les DDOS_Booster qui eux n'ont pas besoin de telegram mais juste d'une requete HTTP avec la cible

**Comment by D3xExtaz** [comment]
ok, par ailleurs ducoup tu pourrais me donner ton telegram?
parce que j'ai developpé un bot ddos pareil mais j'ai quelques problemes eheh

**Comment by Mehliug-git** [comment]
yes https://t.me/mehliug00
